<a href="https://colab.research.google.com/github/Song-Hyunsub/Univ_Study/blob/main/%EC%9D%B8%EA%B3%B5%EC%A7%80%EB%8A%A5/%EB%A8%B8%EC%8B%A0%EB%9F%AC%EB%8B%9D_%EC%9D%B4%ED%95%B4_%EC%8B%A4%EC%8A%B5/%EB%A8%B8%EC%8B%A0%EB%9F%AC%EB%8B%9D_10%EC%B0%A8%EC%8B%9C_%EC%8B%A0%EA%B2%BD%EB%A7%9D_iris.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

# 데이터 제공위치
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"

# 컬럼명 세팅
names = ['sepal-length', 'sepal-width', 'petal-length', 'petal-width', 'Class']

# iris데이터를 읽어오기
irisdata = pd.read_csv(url, names=names)

In [ ]:
irisdata.head()

   sepal-length  sepal-width  petal-length  petal-width        Class
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [ ]:
# 입력값의 분리
X = irisdata.iloc[:, 0:4] # X값 : 4개의 속성

# 타겟값인 class의 분리
y = irisdata.select_dtypes(include=[object]) # Y값 : class

In [ ]:
y.head()

         Class
0  Iris-setosa
1  Iris-setosa
2  Iris-setosa
3  Iris-setosa
4  Iris-setosa

In [ ]:
X.head()

   sepal-length  sepal-width  petal-length  petal-width
0           5.1          3.5           1.4          0.2
1           4.9          3.0           1.4          0.2
2           4.7          3.2           1.3          0.2
3           4.6          3.1           1.5          0.2
4           5.0          3.6           1.4          0.2

In [ ]:
y.Class.unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

=> class 범주형 데이터 3개  
=> 숫자로 바꿔야 함!

In [ ]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder() # LabelEndoer => 숫자로 바꿈

y = y.apply(le.fit_transform)

In [ ]:
y

     Class
0        0
1        0
2        0
3        0
4        0
5        0
6        0
7        0
8        0
9        0
10       0
11       0
12       0
13       0
14       0
15       0
16       0
17       0
18       0
19       0
20       0
21       0
22       0
23       0
24       0
25       0
26       0
27       0
28       0
29       0
..     ...
120      2
121      2
122      2
123      2
124      2
125      2
126      2
127      2
128      2
129      2
130      2
131      2
132      2
133      2
134      2
135      2
136      2
137      2
138      2
139      2
140      2
141      2
142      2
143      2
144      2
145      2
146      2
147      2
148      2
149      2

[150 rows x 1 columns]

In [ ]:
from sklearn.model_selection import train_test_split
# train_test_split : train 데이터와 test 데이터를 나누는 것
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20)
# train 데이터는 보통 70%~80%로 정한다.

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X_train)

X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [ ]:
X_train

array([[-1.18623142e+00, -1.01688952e-01, -1.25373714e+00,
        -1.36864302e+00],
       [ 2.62708833e-02, -7.67289367e-01,  8.56419383e-01,
         1.02703682e+00],
       [-9.43730961e-01,  3.42044657e-01, -1.36779966e+00,
        -1.23554970e+00],
       [ 6.32522036e-01, -1.21102298e+00,  7.99388126e-01,
         1.02703682e+00],
       [-1.06498119e+00, -1.21102298e+00,  5.14231838e-01,
         7.60850172e-01],
       [-2.16229578e-01, -1.01688952e-01,  5.14231838e-01,
         4.94663523e-01],
       [-9.49793472e-02,  1.67324549e+00, -1.08264337e+00,
        -1.10245637e+00],
       [ 2.33002526e+00, -9.89156171e-01,  1.88298202e+00,
         1.55941012e+00],
       [-1.06498119e+00,  1.20177853e-01, -1.19670589e+00,
        -1.36864302e+00],
       [-9.49793472e-02, -1.21102298e+00,  7.99388126e-01,
         1.16013015e+00],
       [-3.37479808e-01, -1.43288978e+00,  1.15013036e-01,
        -3.77097753e-02],
       [ 8.75022497e-01,  3.42044657e-01,  8.56419383e-01,
         1.16013015e+00],
       [-2.16229578e-01, -7.67289367e-01,  3.43138066e-01,
         2.28476874e-01],
       [-1.30748165e+00,  3.42044657e-01, -1.31076840e+00,
        -1.23554970e+00],
       [-8.22480730e-01,  7.85778267e-01, -1.19670589e+00,
        -1.23554970e+00],
       [-8.22480730e-01,  1.67324549e+00, -1.19670589e+00,
        -1.10245637e+00],
       [ 2.68771344e-01, -1.87662339e+00,  7.99388126e-01,
         4.94663523e-01],
       [-8.22480730e-01,  5.63911462e-01, -1.08264337e+00,
        -8.36269722e-01],
       [ 7.53772266e-01,  3.42044657e-01,  5.14231838e-01,
         4.94663523e-01],
       [ 1.11752296e+00,  1.20177853e-01,  4.57200581e-01,
         3.61570198e-01],
       [-8.22480730e-01, -1.21102298e+00, -3.41237024e-01,
        -3.77097753e-02],
       [ 7.53772266e-01, -3.23555757e-01,  4.00169323e-01,
         2.28476874e-01],
       [ 3.90021575e-01, -1.01688952e-01,  5.71263096e-01,
         3.61570198e-01],
       [ 3.90021575e-01, -5.45422562e-01,  2.29075551e-01,
         2.28476874e-01],
       [-1.06498119e+00, -1.01688952e-01, -1.25373714e+00,
        -1.23554970e+00],
       [-1.18623142e+00,  7.85778267e-01, -9.68580856e-01,
        -1.23554970e+00],
       [-1.67123234e+00, -1.01688952e-01, -1.31076840e+00,
        -1.23554970e+00],
       [-9.49793472e-02, -9.89156171e-01, -5.60807365e-02,
        -1.70803100e-01],
       [ 1.36002342e+00,  1.20177853e-01,  7.42356868e-01,
         4.94663523e-01],
       [ 5.11271805e-01, -3.23555757e-01,  4.00169323e-01,
         2.28476874e-01],
       [-1.06498119e+00,  1.20177853e-01, -1.19670589e+00,
        -1.36864302e+00],
       [ 5.11271805e-01,  7.85778267e-01,  1.02751316e+00,
         1.55941012e+00],
       [-3.37479808e-01, -1.21102298e+00,  2.29075551e-01,
         2.28476874e-01],
       [-2.16229578e-01, -3.23555757e-01,  9.50520958e-04,
         2.28476874e-01],
       [-1.06498119e+00,  1.20177853e-01, -1.19670589e+00,
        -1.36864302e+00],
       [ 1.48127365e+00,  3.42044657e-01,  6.28294353e-01,
         3.61570198e-01],
       [-9.49793472e-02, -1.01688952e-01,  3.43138066e-01,
         9.53835492e-02],
       [ 1.11752296e+00, -1.01688952e-01,  7.99388126e-01,
         7.60850172e-01],
       [ 1.47521114e-01,  3.42044657e-01,  6.85325611e-01,
         8.93943496e-01],
       [ 1.11752296e+00,  5.63911462e-01,  1.19860693e+00,
         1.82559677e+00],
       [ 1.23877319e+00, -5.45422562e-01,  6.85325611e-01,
         3.61570198e-01],
       [-1.42873188e+00,  1.20177853e-01, -1.19670589e+00,
        -1.23554970e+00],
       [-2.16229578e-01, -1.21102298e+00,  1.72044293e-01,
        -3.77097753e-02],
       [ 1.36002342e+00,  1.20177853e-01,  8.56419383e-01,
         1.55941012e+00],
       [ 2.62708833e-02, -7.67289367e-01,  2.86106808e-01,
        -1.70803100e-01],
       [-9.49793472e-02,  3.00444632e+00, -1.19670589e+00,
        -9.69363047e-01],
       [-8.22480730e-01,  1.45137868e+00, -1.19670589e+00,
        -9.69363047e-01],
       [-7.01230500e-01, -7.67289367e-01,  1.72044293e-01,
         3.61570198e-01],
       [ 2.62708833e-02, -7.67289367e-01,  1.72044293e-01,
         9.53835492e-02],
       [-9.43730961e-01,  7.85778267e-01, -1.13967463e+00,
        -9.69363047e-01],
       [-5.79980269e-01,  1.45137868e+00, -1.19670589e+00,
        -1.23554970e+00],
       [ 7.53772266e-01, -5.45422562e-01,  1.14157567e+00,
         1.29322347e+00],
       [-3.37479808e-01, -9.89156171e-01,  4.57200581e-01,
         9.53835492e-02],
       [-3.37479808e-01, -1.65475659e+00,  2.29075551e-01,
         2.28476874e-01],
       [ 2.68771344e-01, -3.23555757e-01,  5.14231838e-01,
         4.94663523e-01],
       [-8.22480730e-01,  1.00764507e+00, -1.25373714e+00,
        -1.23554970e+00],
       [ 7.53772266e-01,  3.42044657e-01,  9.70481898e-01,
         1.55941012e+00],
       [ 6.32522036e-01, -3.23555757e-01,  1.14157567e+00,
         8.93943496e-01],
       [ 2.68771344e-01, -1.87662339e+00,  2.29075551e-01,
        -1.70803100e-01],
       [ 6.32522036e-01, -5.45422562e-01,  8.56419383e-01,
         4.94663523e-01],
       [ 1.60252388e+00, -1.01688952e-01,  1.31266944e+00,
         1.29322347e+00],
       [-3.37479808e-01,  1.00764507e+00, -1.31076840e+00,
        -1.23554970e+00],
       [ 3.90021575e-01, -1.01688952e-01,  7.42356868e-01,
         8.93943496e-01],
       [ 1.23877319e+00,  3.42044657e-01,  1.31266944e+00,
         1.55941012e+00],
       [-1.67123234e+00,  3.42044657e-01, -1.31076840e+00,
        -1.23554970e+00],
       [-4.58730039e-01,  1.45137868e+00, -1.19670589e+00,
        -1.23554970e+00],
       [-9.43730961e-01,  5.63911462e-01, -1.25373714e+00,
        -1.23554970e+00],
       [ 1.23877319e+00, -1.01688952e-01,  1.08454441e+00,
         1.29322347e+00],
       [-1.79248257e+00, -1.01688952e-01, -1.42483092e+00,
        -1.36864302e+00],
       [-1.54998211e+00, -1.65475659e+00, -1.31076840e+00,
        -1.10245637e+00],
       [-1.42873188e+00,  3.42044657e-01, -1.25373714e+00,
        -1.23554970e+00],
       [ 2.33002526e+00, -1.01688952e-01,  1.42673196e+00,
         1.55941012e+00],
       [-9.43730961e-01,  1.00764507e+00, -1.13967463e+00,
        -7.03176398e-01],
       [-2.16229578e-01, -5.45422562e-01,  7.42356868e-01,
         1.16013015e+00],
       [ 9.96272728e-01, -1.01688952e-01,  4.57200581e-01,
         3.61570198e-01],
       [ 2.68771344e-01, -7.67289367e-01,  8.56419383e-01,
         6.27756847e-01],
       [-8.22480730e-01,  1.67324549e+00, -1.13967463e+00,
        -1.23554970e+00],
       [ 8.75022497e-01, -1.01688952e-01,  1.25563819e+00,
         1.42631679e+00],
       [-4.58730039e-01,  1.89511229e+00, -1.31076840e+00,
        -9.69363047e-01],
       [-3.37479808e-01, -1.43288978e+00,  5.79817784e-02,
        -1.70803100e-01],
       [-9.43730961e-01, -1.65475659e+00, -1.70143252e-01,
        -1.70803100e-01],
       [ 5.11271805e-01, -1.87662339e+00,  5.14231838e-01,
         4.94663523e-01],
       [ 1.36002342e+00,  3.42044657e-01,  1.19860693e+00,
         1.55941012e+00],
       [ 3.90021575e-01, -3.23555757e-01,  6.28294353e-01,
         3.61570198e-01],
       [-1.18623142e+00, -1.01688952e-01, -1.25373714e+00,
        -1.10245637e+00],
       [-7.01230500e-01,  1.00764507e+00, -1.19670589e+00,
        -1.23554970e+00],
       [-1.18623142e+00,  7.85778267e-01, -1.13967463e+00,
        -1.23554970e+00],
       [-3.37479808e-01,  2.56071271e+00, -1.25373714e+00,
        -1.23554970e+00],
       [ 1.36002342e+00,  1.20177853e-01,  1.02751316e+00,
         1.29322347e+00],
       [-9.49793472e-02, -5.45422562e-01,  5.14231838e-01,
         2.28476874e-01],
       [-4.58730039e-01,  7.85778267e-01, -1.08264337e+00,
        -1.23554970e+00],
       [ 2.62708833e-02, -9.89156171e-01,  2.29075551e-01,
         9.53835492e-02],
       [-1.67123234e+00, -3.23555757e-01, -1.25373714e+00,
        -1.23554970e+00],
       [ 2.68771344e-01,  7.85778267e-01,  5.14231838e-01,
         6.27756847e-01],
       [ 7.53772266e-01, -7.67289367e-01,  9.70481898e-01,
         1.02703682e+00],
       [ 2.62708833e-02, -7.67289367e-01,  8.56419383e-01,
         1.02703682e+00],
       [ 1.47521114e-01, -1.01688952e-01,  8.56419383e-01,
         8.93943496e-01],
       [ 1.84502434e+00, -3.23555757e-01,  1.54079447e+00,
         8.93943496e-01],
       [ 1.72377411e+00, -1.01688952e-01,  1.25563819e+00,
         6.27756847e-01],
       [-9.43730961e-01,  1.00764507e+00, -1.31076840e+00,
        -1.10245637e+00],
       [-8.22480730e-01,  1.67324549e+00, -9.68580856e-01,
        -9.69363047e-01],
       [ 6.32522036e-01, -1.65475659e+00,  4.57200581e-01,
         2.28476874e-01],
       [-1.30748165e+00,  3.42044657e-01, -1.13967463e+00,
        -1.23554970e+00],
       [ 2.57252572e+00,  1.67324549e+00,  1.59782573e+00,
         1.16013015e+00],
       [ 2.33002526e+00, -5.45422562e-01,  1.76891950e+00,
         1.16013015e+00],
       [ 1.11752296e+00,  1.20177853e-01,  1.14157567e+00,
         1.69250344e+00],
       [ 1.47521114e-01, -1.01688952e-01,  3.43138066e-01,
         4.94663523e-01],
       [-1.06498119e+00, -1.43288978e+00, -1.70143252e-01,
        -1.70803100e-01],
       [-9.43730961e-01,  7.85778267e-01, -1.19670589e+00,
        -1.23554970e+00],
       [ 1.11752296e+00,  5.63911462e-01,  1.19860693e+00,
         1.29322347e+00],
       [ 2.62708833e-02,  2.11697910e+00, -1.36779966e+00,
        -1.23554970e+00],
       [ 8.75022497e-01, -5.45422562e-01,  5.71263096e-01,
         4.94663523e-01],
       [ 3.90021575e-01, -9.89156171e-01,  1.14157567e+00,
         3.61570198e-01],
       [-9.43730961e-01, -2.32035700e+00, -5.60807365e-02,
        -1.70803100e-01],
       [-4.58730039e-01,  7.85778267e-01, -1.19670589e+00,
        -9.69363047e-01],
       [-4.58730039e-01,  1.89511229e+00, -1.08264337e+00,
        -9.69363047e-01],
       [-8.22480730e-01,  1.00764507e+00, -1.25373714e+00,
        -1.10245637e+00],
       [ 2.33002526e+00,  1.67324549e+00,  1.76891950e+00,
         1.42631679e+00],
       [-1.18623142e+00,  1.20177853e-01, -1.13967463e+00,
        -1.23554970e+00],
       [ 7.53772266e-01, -5.45422562e-01,  1.14157567e+00,
         1.42631679e+00]])

In [ ]:
X_test

array([[ 1.72377411,  0.34204466,  1.3697007 ,  0.8939435 ],
       [ 1.11752296,  0.12017785,  0.62829435,  0.49466352],
       [ 1.11752296, -1.21102298,  1.25563819,  0.8939435 ],
       [ 0.39002157, -0.54542256,  0.62829435,  0.09538355],
       [-0.94373096,  1.22951188, -1.25373714, -1.2355497 ],
       [ 0.63252204,  0.78577827,  1.14157567,  1.69250344],
       [ 0.8750225 , -0.10168895,  1.08454441,  0.8939435 ],
       [ 2.20877503, -0.10168895,  1.71188825,  1.29322347],
       [-1.42873188,  1.22951188, -1.48186217, -1.2355497 ],
       [ 0.02627088, -0.54542256,  0.85641938,  1.69250344],
       [-0.21622958, -0.10168895,  0.28610681,  0.22847687],
       [ 0.8750225 , -0.10168895,  0.91345064,  1.16013015],
       [-0.09497935, -0.32355576,  0.34313807,  0.22847687],
       [ 0.99627273, -0.32355576,  0.5712631 ,  0.22847687],
       [-0.45873004, -0.10168895,  0.51423184,  0.49466352],
       [ 1.72377411,  1.22951188,  1.42673196,  1.82559677],
       [ 0.51127181, -0.54542256,  0.68532561,  0.8939435 ],
       [ 0.75377227,  0.12017785,  1.08454441,  0.8939435 ],
       [-0.7012305 ,  0.78577827, -1.25373714, -1.2355497 ],
       [ 1.96627457, -0.54542256,  1.42673196,  1.02703682],
       [-1.42873188,  0.78577827, -1.25373714, -1.10245637],
       [-0.7012305 ,  2.3388459 , -1.19670589, -1.36864302],
       [-0.94373096, -0.10168895, -1.13967463, -1.2355497 ],
       [ 0.63252204,  0.56391146,  1.3697007 ,  1.82559677],
       [-0.09497935, -0.54542256,  0.28610681,  0.22847687],
       [ 0.26877134, -0.10168895,  0.68532561,  0.8939435 ],
       [ 0.63252204, -0.76728937,  0.74235687,  0.8939435 ],
       [ 0.63252204,  0.56391146,  0.62829435,  0.62775685],
       [ 1.11752296, -0.10168895,  0.91345064,  1.55941012],
       [ 0.63252204, -1.21102298,  0.74235687,  0.49466352]])

In [ ]:
from sklearn.neural_network import MLPClassifier
mlp = MLPClassifier(hidden_layer_sizes=(10, 10, 10), max_iter=1000)
# layer 3, 학습반복 1000번
mlp.fit(X_train, y_train.values.ravel())

MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(10, 10, 10), learning_rate='constant',
       learning_rate_init=0.001, max_iter=1000, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=None,
       shuffle=True, solver='adam', tol=0.0001, validation_fraction=0.1,
       verbose=False, warm_start=False)

=> 값을 직접 정해줄 수도 있음

In [ ]:
y_train

     Class
12       0
142      2
35       0
146      2
106      2
66       1
18       0
118      2
34       0
113      2
80       1
110      2
94       1
2        0
39       0
19       0
119      2
23       0
51       1
65       1
98       1
74       1
91       1
71       1
1        0
24       0
38       0
79       1
52       1
97       1
..     ...
20       0
92       1
8        0
85       1
111      2
101      2
149      2
107      2
129      2
40       0
44       0
87       1
29       0
131      2
122      2
140      2
61       1
57       1
7        0
124      2
14       0
54       1
134      2
60       1
31       0
5        0
17       0
117      2
30       0
132      2

[120 rows x 1 columns]

In [ ]:
y_train.values.ravel()

array([0, 2, 0, 2, 2, 1, 0, 2, 0, 2, 1, 2, 1, 0, 0, 0, 2, 0, 1, 1, 1, 1,
       1, 1, 0, 0, 0, 1, 1, 1, 0, 2, 1, 1, 0, 1, 1, 1, 1, 2, 1, 0, 1, 2,
       1, 0, 0, 1, 1, 0, 0, 2, 1, 1, 1, 0, 2, 2, 1, 2, 2, 0, 2, 2, 0, 0,
       0, 2, 0, 0, 0, 2, 0, 2, 1, 1, 0, 2, 0, 1, 1, 1, 2, 1, 0, 0, 0, 0,
       2, 1, 0, 1, 0, 1, 2, 2, 2, 2, 2, 0, 0, 1, 0, 2, 2, 2, 1, 1, 0, 2,
       0, 1, 2, 1, 0, 0, 0, 2, 0, 2], dtype=int64)

In [ ]:
X_test

array([[ 1.59865978,  1.38427656,  1.29012717,  1.68070737],
       [-1.55021555,  0.89498882, -1.40580363, -1.22884506],
       [-1.30799437,  0.16105721, -1.29108317, -1.36109744],
       [ 0.2664433 , -0.57287439,  0.48708395, -0.03857361],
       [ 0.99310683,  0.16105721,  0.48708395,  0.35818354],
       [-0.21799906,  3.34142752, -1.3484434 , -1.09659268],
       [-1.67132614, -1.79609374, -1.46316386, -1.22884506],
       [-0.9446626 ,  1.8735643 , -1.29108317, -1.36109744],
       [ 0.02422212,  0.40570108,  0.54444418,  0.75494069],
       [-0.9446626 ,  1.8735643 , -1.11900248, -1.09659268],
       [-0.58133083,  0.89498882, -1.3484434 , -1.09659268],
       [-0.33910965, -1.306806  ,  0.02820211, -0.170826  ],
       [ 0.75088566, -0.08358666,  0.7738851 ,  1.01944545],
       [-0.9446626 ,  0.65034495, -1.23372294, -0.96434029],
       [-1.06577319, -2.53002535, -0.20123881, -0.30307838],
       [-0.33910965, -0.08358666,  0.37236349,  0.35818354],
       [ 0.62977507, -0.57287439,  1.00332602,  1.15169784],
       [ 2.20421273,  1.8735643 ,  1.63428855,  1.28395022],
       [-0.58133083,  2.11820817, -1.46316386, -1.09659268],
       [-1.79243673,  0.40570108, -1.46316386, -1.36109744],
       [ 1.11421742, -0.08358666,  0.94596579,  1.15169784],
       [-0.58133083,  1.62892043, -1.3484434 , -1.36109744],
       [ 0.50866448, -0.81751826,  0.60180441,  0.75494069],
       [ 0.99310683, -0.08358666,  0.65916464,  0.6226883 ],
       [-1.18688378,  0.16105721, -1.3484434 , -1.49334983],
       [-1.18688378, -0.08358666, -1.40580363, -1.36109744],
       [-0.21799906, -1.06216213, -0.20123881, -0.30307838],
       [-0.09688847, -0.81751826,  0.02820211, -0.03857361],
       [-0.33910965, -0.57287439,  0.60180441,  1.01944545],
       [ 0.14533271, -0.08358666,  0.54444418,  0.75494069]])

In [ ]:
predictions = mlp.predict(X_test)
predictions

array([2, 1, 2, 1, 0, 2, 2, 2, 0, 2, 1, 2, 1, 1, 1, 2, 2, 2, 0, 2, 0, 0,
       0, 2, 1, 2, 2, 1, 2, 1], dtype=int64)

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,predictions))   # 혼돈 행렬의 2가지 변수 : 실제값 , 예측값
print(classification_report(y_test,predictions))

[[ 6  0  0]
 [ 0  9  0]
 [ 0  0 15]]
             precision    recall  f1-score   support

          0       1.00      1.00      1.00         6
          1       1.00      1.00      1.00         9
          2       1.00      1.00      1.00        15

avg / total       1.00      1.00      1.00        30

=> 대각선 방향으로 숫자가 모여있어야 함